server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Sirve la aplicación Angular en /saludo/
    location /saludo/ {
        alias /usr/share/nginx/html/saludo/;
        try_files $uri $uri/ /saludo/index.html?$args;
    }

    # Opcional: redirige /saludo a /saludo/
    location = /saludo {
        return 301 /saludo/;
    }
}